//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHARMA-AGENCIES")]
        public string oRGNIZATIONnAME {
            get {
                return ((string)(this["oRGNIZATIONnAME"]));
            }
            set {
                this["oRGNIZATIONnAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09ADIFS6223L1ZM")]
        public string GSTN {
            get {
                return ((string)(this["GSTN"]));
            }
            set {
                this["GSTN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sarnath-Varanasi(221007)")]
        public string aDDRESS {
            get {
                return ((string)(this["aDDRESS"]));
            }
            set {
                this["aDDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Behind Korean Temple,Harsh Nagar Colony")]
        public string fULLaDDRESS {
            get {
                return ((string)(this["fULLaDDRESS"]));
            }
            set {
                this["fULLaDDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020")]
        public string fINANCIALyEAR {
            get {
                return ((string)(this["fINANCIALyEAR"]));
            }
            set {
                this["fINANCIALyEAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int rECEIPTnO {
            get {
                return ((int)(this["rECEIPTnO"]));
            }
            set {
                this["rECEIPTnO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 700")]
        public global::System.Drawing.Size rECEIPTsIZE {
            get {
                return ((global::System.Drawing.Size)(this["rECEIPTsIZE"]));
            }
            set {
                this["rECEIPTsIZE"] = value;
            }
        }
    }
}
